menu:
  # dashboard:
  #   name: dashboard
  #   url_path: /admin/dashboard
  #   icon: dashboard
  #   current: ['keppler_ga_dashboard/dashboard']
  # seo:
  #   name: SEO
  #   current: ['admin/meta_tags', 'admin/google_adwords']
  #   icon: code
  #   model: MetaTag
  #   submenu:
  #     - meta_tags:
  #         name: 'Title & Metas'
  #         url_path: /admin/meta_tags
  #         current: ['admin/meta_tags']
  #     - google_adwords:
  #         name: Google Adwords
  #         url_path: /admin/google_adwords
  #         current: ['admin/google_adwords']
  # google_analytics_track:
  #   name: google analytics tracks
  #   url_path: /admin/google_analytics_tracks
  #   icon: insert_chart
  #   current: ['admin/google_analytics_tracks']
  #   model: GoogleAnalyticsTrack
  state:
    name: states
    url_path: /admin/states
    icon: insert_chart
    current: ['admin/states']
    model: State
  asignation:
    name: asignations
    url_path: /admin/asignations
    icon: assignment_turned_in
    current: ['admin/asignations']
    model: Asignation
  payment:
    name: payments
    url_path: /admin/payments
    icon: assignment
    current: ['admin/payments']
    model: Payment
  percentage_cost:
    name: percentage costs
    url_path: /admin/percentage_costs
    icon: insert_chart
    current: ['admin/percentage_costs']
    model: PercentageCost
  stack_bank:
    name: stack banks
    url_path: /admin/stack_banks
    icon: insert_chart
    current: ['admin/stack_banks']
    model: StackBank
  user:
    name: users
    url_path: /admin/users
    icon: account_circle
    current: ["admin/users"]
    model: User
  report:
    name: Reports
    icon: description
    current: ['admin/reports']
    model: Asignation
    submenu:
      - asignation:
          name: Report General
          url_path: /admin/asignations/report
          current: ['admin/asignations/report']
      - asignation:
          name: Report Orders
          url_path: /admin/asignations/report_order
          current: ['admin/asignations/report_order']
  customize:
    name: keppler design
    icon: color_lens
    current: ['admin/customizes']
    model: Customize
    submenu:
      - customize:
          name: frontend templates
          url_path: /admin/customizes
          current: ['admin/customizes']
      - appearance:
          name: admin appearance
          url_path: /admin/settings/appearance
          current: ['appearance']
  # setting:
  #   name: setting
  #   current: ['admin/settings']
  #   icon: settings
  #   model: Setting
  #   submenu:
  #     - basic_information:
  #         name: Basic information
  #         url_path: /admin/settings/basic_information
  #         current: ['basic_information']
  #     - smtp_setting:
  #         name: Email setting (SMTP)
  #         url_path: /admin/settings/email_setting
  #         current: ['email_setting']
  #     - google_analytics_setting:
  #         name: Google analytics
  #         url_path: /admin/settings/google_analytics_setting
  #         current: ['google_analytics_setting']
  #     - social_account:
  #         name: Social Accounts
  #         url_path: /admin/settings/social_accounts
  #         current: ['social_accounts']
